// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLpbr2aTApmkdvdLY_fOjBehP_WP8afwE',
    appId: '1:580337037636:web:199a8d080d5aad5e9aa711',
    messagingSenderId: '580337037636',
    projectId: 'hedity-app',
    authDomain: 'hedity-app.firebaseapp.com',
    storageBucket: 'hedity-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5RdLNnCg0M3YjR9TahcuwHsYs-lw_iIs',
    appId: '1:580337037636:android:0b0aef429439a38b9aa711',
    messagingSenderId: '580337037636',
    projectId: 'hedity-app',
    storageBucket: 'hedity-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiwICbp8_pXxxBTjDHOWzN41hYa6BUJ5g',
    appId: '1:580337037636:ios:bab1f2304570c40d9aa711',
    messagingSenderId: '580337037636',
    projectId: 'hedity-app',
    storageBucket: 'hedity-app.firebasestorage.app',
    iosBundleId: 'com.example.hedityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLpbr2aTApmkdvdLY_fOjBehP_WP8afwE',
    appId: '1:580337037636:web:27d8acfabfb999a89aa711',
    messagingSenderId: '580337037636',
    projectId: 'hedity-app',
    authDomain: 'hedity-app.firebaseapp.com',
    storageBucket: 'hedity-app.firebasestorage.app',
  );
}
